import type { WorkerErrorMsg } from "../../define-worker/define-worker";

export interface RequestOptions {
  /** Milliseconds before the Promise rejects with WorkerTimeoutError. */
  timeoutMs?: number;
}

export class WorkerTimeoutError extends Error {
  readonly timeoutMs: number;
  constructor(timeoutMs: number) {
    super(`Worker request timed out after ${timeoutMs}ms`);
    this.name = "WorkerTimeoutError";
    this.timeoutMs = timeoutMs;
  }

  /** Type-safe alternative to `instanceof WorkerTimeoutError`. */
  static is(e: unknown): e is WorkerTimeoutError {
    return e instanceof WorkerTimeoutError;
  }
}

/**
 * Error thrown by `request()` / `dispatch()` when the worker handler throws.
 * Preserves the worker-side stack trace as `workerStack` so callers can
 * see where the error originated inside the worker.
 */
export class WorkerHandlerError extends Error {
  readonly workerStack?: string;
  constructor(message: string, workerStack?: string) {
    super(message);
    this.name = "WorkerHandlerError";
    this.workerStack = workerStack;
  }

  /** Type-safe alternative to `instanceof WorkerHandlerError`. */
  static is(e: unknown): e is WorkerHandlerError {
    return e instanceof WorkerHandlerError;
  }
}

export interface WorkerPoolStats {
  readonly size: number;
  readonly hostCounts: readonly number[];
  readonly leastBusyIndex: number;
  readonly totalActive: number;
}

export interface WorkerLike {
  postMessage(msg: unknown, transfer?: Transferable[]): void;
  terminate(): void;
}

export interface WorkerPoolOptions {
  /** Number of workers to maintain. Default: 4. Clamped to [1, 16]. */
  size?: number;
  /**
   * Factory function that creates a new Worker instance.
   * Required — the pool has no default because the worker script URL
   * is package-specific and must be provided by the caller.
   *
   * @example
   * // In a bundler environment (Vite, webpack, etc.):
   * workerFactory: () => new Worker(new URL("./my-worker.js", import.meta.url), { type: "module" })
   */
  workerFactory: () => Worker;
}

let _standaloneSeq = 0;

export class WorkerHandle<TMsg extends object> implements WorkerLike {
  private _terminated = false;
  private readonly _ownsWorker: boolean;
  // Map<type, Map<original listener, wrapper listener>> for O(1) remove
  private readonly _listenerMap = new Map<
    string,
    Map<EventListener, EventListener>
  >();
  // Abort callbacks registered by pending request() calls
  private readonly _abortCallbacks = new Set<() => void>();

  protected readonly _worker: Worker;
  readonly hostId: string;
  private readonly _onRelease?: () => void;

  /**
   * Standalone usage — the handle owns the Worker lifecycle.
   * `terminate()` will stop the worker automatically.
   *
   * @example
   * const handle = new WorkerHandle<MyMsg>(
   *   () => new Worker(new URL("./my-worker.ts", import.meta.url), { type: "module" })
   * );
   * handle.postMessage({ ... });
   * handle.terminate(); // stops the worker
   */
  constructor(workerFactory: () => Worker);
  /**
   * Pool-backed usage — the pool owns the Worker lifecycle.
   * `terminate()` is a no-op; call `release()` when done.
   *
   * @param worker - Worker instance managed by the pool.
   * @param hostId - Unique identifier generated by the pool.
   * @param onRelease - Pool's busy-counter decrement callback.
   */
  constructor(worker: Worker, hostId: string, onRelease?: () => void);
  constructor(
    workerOrFactory: Worker | (() => Worker),
    hostId?: string,
    onRelease?: () => void,
  ) {
    if (typeof workerOrFactory === "function") {
      this._worker = workerOrFactory();
      this.hostId = `standalone-${++_standaloneSeq}`;
      this._ownsWorker = true;
    } else {
      this._worker = workerOrFactory;
      this.hostId = hostId!;
      this._ownsWorker = false;
    }
    this._onRelease = onRelease;
  }

  /**
   * Subscribe to worker→main messages that belong to this host.
   * Filters by `hostId` so multiple hosts sharing a single worker
   * each only see their own messages.
   */
  addEventListener(type: string, listener: EventListener): void {
    const id = this.hostId;
    const wrapper: EventListener = (evt: Event) => {
      const msg = (evt as MessageEvent<{ hostId?: string; __fluxionError?: true }>).data;
      if (
        msg !== null &&
        typeof msg === "object" &&
        msg.hostId === id &&
        !msg.__fluxionError
      ) {
        listener(evt);
      }
    };
    let byType = this._listenerMap.get(type);
    if (!byType) {
      byType = new Map();
      this._listenerMap.set(type, byType);
    }
    byType.set(listener, wrapper);
    this._worker.addEventListener(type, wrapper);
  }

  /**
   * Subscribe to worker→main messages with a typed callback.
   * Returns an `off` function — call it to unsubscribe.
   *
   * @example — fire-once (request/response)
   * ```ts
   * const off = handle.onMessage<MyResult>((msg) => {
   *   off();
   *   console.log(msg.result);
   * });
   * handle.postMessage({ op: "sum", values });
   * ```
   *
   * @example — persistent subscription
   * ```ts
   * const off = handle.onMessage<MyResult>((msg) => {
   *   setResult(msg.result);
   * });
   * // later: off();
   * ```
   */
  onMessage<TResult extends object = object>(
    callback: (msg: TResult) => void,
  ): () => void {
    const listener: EventListener = (evt: Event) => {
      callback((evt as MessageEvent<TResult>).data);
    };
    this.addEventListener("message", listener);
    return () => this.removeEventListener("message", listener);
  }

  /**
   * Send a message and await a single response. Automatically unsubscribes
   * after the first reply or error. `release()` is still the caller's responsibility.
   */
  request<TResult extends object = object>(
    msg: TMsg,
    opts?: RequestOptions,
    transfer?: Transferable[],
  ): Promise<TResult> {
    return new Promise<TResult>((resolve, reject) => {
      let timerId: ReturnType<typeof setTimeout> | undefined;

      const cleanup = () => {
        if (timerId !== undefined) clearTimeout(timerId);
        offMsg();
        offErr();
        this._abortCallbacks.delete(abort);
      };

      const abort = () => {
        cleanup();
        reject(new Error("Worker was terminated"));
      };
      this._abortCallbacks.add(abort);

      const offMsg = this.onMessage<TResult>((result) => {
        cleanup();
        resolve(result);
      });

      const offErr = this.onError((err) => {
        cleanup();
        reject(new WorkerHandlerError(err.message, err.stack));
      });

      if (opts?.timeoutMs !== undefined) {
        const ms = opts.timeoutMs;
        timerId = setTimeout(() => {
          cleanup();
          reject(new WorkerTimeoutError(ms));
        }, ms);
      }

      this.postMessage(msg, transfer);
    });
  }

  /**
   * Subscribe to errors reported by the worker handler via defineWorker.
   * Registered under the internal "__fluxion:error" key so _markTerminated()
   * cleans it up alongside normal message listeners.
   * Returns an `off` unsubscribe function.
   */
  onError(callback: (err: WorkerErrorMsg) => void): () => void {
    const id = this.hostId;
    const raw: EventListener = (evt: Event) => {
      const data = (evt as MessageEvent).data;
      if (
        data !== null &&
        typeof data === "object" &&
        (data as WorkerErrorMsg).__fluxionError === true &&
        (data as WorkerErrorMsg).hostId === id
      ) {
        callback(data as WorkerErrorMsg);
      }
    };
    // Store under "message" key (same event type) so _markTerminated() removes it correctly
    let byType = this._listenerMap.get("message");
    if (!byType) {
      byType = new Map();
      this._listenerMap.set("message", byType);
    }
    byType.set(raw, raw);
    this._worker.addEventListener("message", raw);
    return () => {
      this._worker.removeEventListener("message", raw);
      const map = this._listenerMap.get("message");
      if (map) {
        map.delete(raw);
        if (map.size === 0) this._listenerMap.delete("message");
      }
    };
  }

  removeEventListener(type: string, listener: EventListener): void {
    const byType = this._listenerMap.get(type);
    const wrapper = byType?.get(listener);
    if (wrapper) {
      this._worker.removeEventListener(type, wrapper);
      byType!.delete(listener);
      if (byType!.size === 0) this._listenerMap.delete(type);
    }
  }

  /**
   * Stamp `hostId` onto the message and forward to the worker.
   * Sends a shallow-copied object so the caller's input is never mutated
   * — this also makes the same message object safely reusable across handles.
   * The shallow-copy cost is negligible compared to structured clone serialization.
   */
  postMessage(msg: TMsg, transfer?: Transferable[]): void {
    if (this._terminated) return;
    const stamped = { ...msg, hostId: this.hostId };
    if (transfer && transfer.length > 0) {
      this._worker.postMessage(stamped, transfer);
    } else {
      this._worker.postMessage(stamped);
    }
  }

  /**
   * Signal that this host is done with the current job.
   * When backed by a pool, decrements the busy counter so the worker can be reused.
   * When used standalone (no pool), this is a no-op — call `worker.terminate()` directly.
   */
  release(): void {
    this._onRelease?.();
  }

  /**
   * When the handle owns the worker (factory constructor), stops the worker
   * and cleans up all listeners. When pool-backed, this is a no-op — the pool
   * manages the worker lifetime.
   */
  terminate(): void {
    if (this._ownsWorker) {
      this._markTerminated();
      this._worker.terminate();
    }
  }

  /**
   * Universal cleanup — works the same regardless of mode.
   * - Standalone: stops the worker (same as `terminate()`).
   * - Pool-backed: releases the slot back to the pool (same as `release()`).
   *
   * Prefer `dispose()` over `release()`/`terminate()` when the calling code
   * doesn't need to know which mode the handle is in.
   */
  dispose(): void {
    if (this._ownsWorker) {
      this._markTerminated();
      this._worker.terminate();
    } else {
      this._markTerminated();
      this._onRelease?.();
    }
  }

  _markTerminated(): void {
    this._terminated = true;
    for (const abort of this._abortCallbacks) abort();
    this._abortCallbacks.clear();
    for (const [type, byType] of this._listenerMap) {
      for (const wrapper of byType.values()) {
        this._worker.removeEventListener(type, wrapper);
      }
    }
    this._listenerMap.clear();
  }
}

export class WorkerPool<TMsg extends object> {
  private readonly workers: Worker[];
  private readonly hostCounts: Int32Array;
  private readonly handles: Set<WorkerHandle<TMsg>> = new Set();
  private _seq = 0;
  private _disposed = false;

  constructor(opts: WorkerPoolOptions) {
    const size = Math.max(1, Math.min(opts.size ?? 4, 16));
    this.workers = Array.from({ length: size }, () => opts.workerFactory());
    // Int32Array for cache-friendly integer counters
    this.hostCounts = new Int32Array(size);
  }

  /**
   * Convenience method: acquire a handle, send one request, release, and return the result.
   * Equivalent to `acquire() → request() → release()` in a try/finally block.
   *
   * @example
   * ```ts
   * const result = await pool.dispatch<CalcResultMsg>(
   *   { op: "sum", values },
   *   { timeoutMs: 5000 },
   * );
   * ```
   */
  async dispatch<TResult extends object = object>(
    msg: TMsg,
    opts?: RequestOptions,
    transfer?: Transferable[],
  ): Promise<TResult> {
    const handle = this.acquire();
    try {
      return await handle.request<TResult>(msg, opts, transfer);
    } finally {
      handle.release();
    }
  }

  acquire(): WorkerHandle<TMsg> {
    if (this._disposed) {
      throw new Error("WorkerPool has been disposed");
    }
    const index = this._leastBusyIndex();
    this.hostCounts[index]++;
    const hostId = `host-${++this._seq}`;
    const handle = this._createHandle(this.workers[index]!, index, hostId);
    this.handles.add(handle);
    return handle;
  }

  /** Override in subclasses to return a custom handle type. */
  protected _createHandle(
    worker: Worker,
    index: number,
    hostId: string,
  ): WorkerHandle<TMsg> {
    const handle = new WorkerHandle<TMsg>(worker, hostId, () => {
      this.handles.delete(handle);
      this._release(index);
    });
    return handle;
  }

  _release(workerIndex: number): void {
    if (this._disposed) return;
    const current = this.hostCounts[workerIndex];
    if (current !== undefined && current > 0) this.hostCounts[workerIndex]--;
  }

  dispose(): void {
    if (this._disposed) return;
    this._disposed = true;
    for (const handle of this.handles) {
      handle._markTerminated();
    }
    this.handles.clear();
    for (const worker of this.workers) {
      worker.terminate();
    }
  }

  stats(): WorkerPoolStats {
    const size = this.hostCounts.length;
    let leastBusyIndex = 0;
    let minCount = this.hostCounts[0]!;
    let totalActive = 0;
    const hostCounts: number[] = new Array(size);
    for (let i = 0; i < size; i++) {
      const c = this.hostCounts[i]!;
      hostCounts[i] = c;
      totalActive += c;
      if (c < minCount) {
        minCount = c;
        leastBusyIndex = i;
      }
    }
    return { size, hostCounts, leastBusyIndex, totalActive };
  }

  private _leastBusyIndex(): number {
    const counts = this.hostCounts;
    let minIdx = 0;
    let minCount = counts[0]!;
    for (let i = 1; i < counts.length; i++) {
      const c = counts[i]!;
      if (c < minCount) {
        minCount = c;
        minIdx = i;
      }
    }
    return minIdx;
  }
}
