export interface WorkerLike {
  postMessage(msg: unknown, transfer?: Transferable[]): void;
  terminate(): void;
}

export interface WorkerPoolOptions {
  /** Number of workers to maintain. Default: 4. Clamped to [1, 16]. */
  size?: number;
  /**
   * Factory function that creates a new Worker instance.
   * Required — the pool has no default because the worker script URL
   * is package-specific and must be provided by the caller.
   *
   * @example
   * // In a bundler environment (Vite, webpack, etc.):
   * workerFactory: () => new Worker(new URL("./my-worker.js", import.meta.url), { type: "module" })
   */
  workerFactory: () => Worker;
}

let _standaloneSeq = 0;

export class WorkerHandle<TMsg extends object> implements WorkerLike {
  private _terminated = false;
  private readonly _ownsWorker: boolean;
  // Map<type, Map<original listener, wrapper listener>> for O(1) remove
  private readonly _listenerMap = new Map<
    string,
    Map<EventListener, EventListener>
  >();

  protected readonly _worker: Worker;
  readonly hostId: string;
  private readonly _onRelease?: () => void;

  /**
   * Standalone usage — the handle owns the Worker lifecycle.
   * `terminate()` will stop the worker automatically.
   *
   * @example
   * const handle = new WorkerHandle<MyMsg>(
   *   () => new Worker(new URL("./my-worker.ts", import.meta.url), { type: "module" })
   * );
   * handle.postMessage({ ... });
   * handle.terminate(); // stops the worker
   */
  constructor(workerFactory: () => Worker);
  /**
   * Pool-backed usage — the pool owns the Worker lifecycle.
   * `terminate()` is a no-op; call `release()` when done.
   *
   * @param worker - Worker instance managed by the pool.
   * @param hostId - Unique identifier generated by the pool.
   * @param onRelease - Pool's busy-counter decrement callback.
   */
  constructor(worker: Worker, hostId: string, onRelease?: () => void);
  constructor(
    workerOrFactory: Worker | (() => Worker),
    hostId?: string,
    onRelease?: () => void,
  ) {
    if (typeof workerOrFactory === "function") {
      this._worker = workerOrFactory();
      this.hostId = `standalone-${++_standaloneSeq}`;
      this._ownsWorker = true;
    } else {
      this._worker = workerOrFactory;
      this.hostId = hostId!;
      this._ownsWorker = false;
    }
    this._onRelease = onRelease;
  }

  /**
   * Subscribe to worker→main messages that belong to this host.
   * Filters by `hostId` so multiple hosts sharing a single worker
   * each only see their own messages.
   */
  addEventListener(type: string, listener: EventListener): void {
    const id = this.hostId;
    const wrapper: EventListener = (evt: Event) => {
      const msg = (evt as MessageEvent<{ hostId?: string }>).data;
      if (msg !== null && typeof msg === "object" && msg.hostId === id) {
        listener(evt);
      }
    };
    let byType = this._listenerMap.get(type);
    if (!byType) {
      byType = new Map();
      this._listenerMap.set(type, byType);
    }
    byType.set(listener, wrapper);
    this._worker.addEventListener(type, wrapper);
  }

  /**
   * Subscribe to worker→main messages with a typed callback.
   * Returns an `off` function — call it to unsubscribe.
   *
   * @example — fire-once (request/response)
   * ```ts
   * const off = handle.onMessage<MyResult>((msg) => {
   *   off();
   *   console.log(msg.result);
   * });
   * handle.postMessage({ op: "sum", values });
   * ```
   *
   * @example — persistent subscription
   * ```ts
   * const off = handle.onMessage<MyResult>((msg) => {
   *   setResult(msg.result);
   * });
   * // later: off();
   * ```
   */
  onMessage<TResult extends object = object>(
    callback: (msg: TResult) => void,
  ): () => void {
    const listener: EventListener = (evt: Event) => {
      callback((evt as MessageEvent<TResult>).data);
    };
    this.addEventListener("message", listener);
    return () => this.removeEventListener("message", listener);
  }

  removeEventListener(type: string, listener: EventListener): void {
    const byType = this._listenerMap.get(type);
    const wrapper = byType?.get(listener);
    if (wrapper) {
      this._worker.removeEventListener(type, wrapper);
      byType!.delete(listener);
      if (byType!.size === 0) this._listenerMap.delete(type);
    }
  }

  /**
   * Stamp `hostId` onto the message and forward to the worker.
   * Avoids object spread allocation on the hot path by mutating the message
   * in-place — safe because `postMessage` serializes synchronously.
   */
  postMessage(msg: TMsg, transfer?: Transferable[]): void {
    if (this._terminated) return;
    (msg as TMsg & { hostId: string }).hostId = this.hostId;
    if (transfer && transfer.length > 0) {
      this._worker.postMessage(msg, transfer);
    } else {
      this._worker.postMessage(msg);
    }
  }

  /**
   * Signal that this host is done with the current job.
   * When backed by a pool, decrements the busy counter so the worker can be reused.
   * When used standalone (no pool), this is a no-op — call `worker.terminate()` directly.
   */
  release(): void {
    this._onRelease?.();
  }

  /**
   * When the handle owns the worker (factory constructor), stops the worker
   * and cleans up all listeners. When pool-backed, this is a no-op — the pool
   * manages the worker lifetime.
   */
  terminate(): void {
    if (this._ownsWorker) {
      this._markTerminated();
      this._worker.terminate();
    }
  }

  _markTerminated(): void {
    this._terminated = true;
    for (const [type, byType] of this._listenerMap) {
      for (const wrapper of byType.values()) {
        this._worker.removeEventListener(type, wrapper);
      }
    }
    this._listenerMap.clear();
  }
}

export class WorkerPool<TMsg extends object> {
  private readonly workers: Worker[];
  private readonly hostCounts: Int32Array;
  private readonly handles: Set<WorkerHandle<TMsg>> = new Set();
  private _seq = 0;
  private _disposed = false;

  constructor(opts: WorkerPoolOptions) {
    const size = Math.max(1, Math.min(opts.size ?? 4, 16));
    this.workers = Array.from({ length: size }, () => opts.workerFactory());
    // Int32Array for cache-friendly integer counters
    this.hostCounts = new Int32Array(size);
  }

  acquire(): WorkerHandle<TMsg> {
    if (this._disposed) {
      throw new Error("WorkerPool has been disposed");
    }
    const index = this._leastBusyIndex();
    this.hostCounts[index]++;
    const hostId = `host-${++this._seq}`;
    const handle = this._createHandle(this.workers[index]!, index, hostId);
    this.handles.add(handle);
    return handle;
  }

  /** Override in subclasses to return a custom handle type. */
  protected _createHandle(
    worker: Worker,
    index: number,
    hostId: string,
  ): WorkerHandle<TMsg> {
    return new WorkerHandle<TMsg>(worker, hostId, () => this._release(index));
  }

  _release(workerIndex: number): void {
    const current = this.hostCounts[workerIndex];
    if (current !== undefined && current > 0) this.hostCounts[workerIndex]--;
  }

  dispose(): void {
    if (this._disposed) return;
    this._disposed = true;
    for (const handle of this.handles) {
      handle._markTerminated();
    }
    this.handles.clear();
    for (const worker of this.workers) {
      worker.terminate();
    }
  }

  private _leastBusyIndex(): number {
    const counts = this.hostCounts;
    let minIdx = 0;
    let minCount = counts[0]!;
    for (let i = 1; i < counts.length; i++) {
      const c = counts[i]!;
      if (c < minCount) {
        minCount = c;
        minIdx = i;
      }
    }
    return minIdx;
  }
}
